In [ ]:
import numpy as  np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Copy of Customer Call List.xlsx")

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [ ]:
df.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

In [ ]:
df = df.drop(["Not_Useful_Column"],axis = 1)

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No

In [ ]:
df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
df.duplicated().sum()

1

In [ ]:
df.replace("N/a","")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,,,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
df.isnull().sum()

CustomerID         0
First_Name         0
Last_Name          1
Phone_Number       2
Address            0
Paying Customer    0
Do_Not_Contact     4
dtype: int64

In [ ]:
df["Last_Name"] = df["Last_Name"].str.replace(r'^[^\w]', '', regex=True)

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No

In [ ]:
df["Phone_Number"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 21 entries, 0 to 20
Series name: Phone_Number
Non-Null Count  Dtype
--------------  -----
19 non-null     object
dtypes: object(1)
memory usage: 300.0+ bytes

In [ ]:
df["Phone_Number"] = df['Phone_Number'].astype(str).str.replace(r'\D', '', regex=True)

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No

In [ ]:
df["Phone_Number"] = df['Phone_Number'].astype(str).str[:3]+ '-' + df['Phone_Number'].astype(str).str[3:6] +'-'+ df['Phone_Number'].astype(str).str[6:9]

In [ ]:
df.drop(["Phone_Number"],axis = 1)

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,93 West Main Street,No,Yes
2,1003,Walter,White,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,123 Dragons Road,Y,No
5,1006,Ron,Swanson,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,1209 South Street,No,No
7,1008,Sherlock,Holmes,98 Clue Drive,N,No
8,1009,Gandalf,NaN,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,..Potter,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,2039 Main Street,Yes,N
13,1014,Leslie,Knope,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,214 HR Avenue,N,No
15,1016,Ron,Weasley,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,Yes
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Yes,N

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

CustomerID         0
First_Name         0
Last_Name          0
Phone_Number       0
Address            0
Paying Customer    0
Do_Not_Contact     0
dtype: int64

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes

In [ ]:
df[["zip_code", "street"]] = df["Address"].str.split(',', n=1, expand=True)

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,zip_code,street
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No,123 Dragons Road,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,zip_code,street
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No,123 Dragons Road,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,1209 South Street,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,No,98 Clue Drive,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N,2039 Main Street,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None
14,1015,Toby,Flenderson_,304-762-246,214 HR Avenue,N,No,214 HR Avenue,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine
20,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine

In [ ]:
df["Phone_Number"] = df["Phone_Number"].str.replace("--"," ")

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,zip_code,street
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No,123 Dragons Road,None
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,No,98 Clue Drive,None
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N,2039 Main Street,None
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None
14,1015,Toby,Flenderson_,304-762-246,214 HR Avenue,N,No,214 HR Avenue,None
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine
20,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine

In [ ]:
df['Zip_Code'] = df['zip_code'].astype(str).str.extract(r'(\d+)', expand=False)

In [ ]:
df['Street_Address'] = df['zip_code'].astype(str).str.extract(r'([A-Za-z]+)', expand=False)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,zip_code,street,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,123,Shire
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,None,93,West
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,"Pennsylvania, 18503",980,Paper
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No,123 Dragons Road,None,123,Dragons
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,None,768,City
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,1209,South
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,No,98 Clue Drive,None,98,Clue
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,25,th
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,612,Shire
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N,2039 Main Street,None,2039,Main
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,None,343,City
14,1015,Toby,Flenderson_,304-762-246,214 HR Avenue,N,No,214 HR Avenue,None,214,HR
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,2395,Hogwarts
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,121,Paper
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,NaN,N
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,910,Tatooine
20,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,910,Tatooine

In [ ]:
df.drop(["Address","zip_code","Phone_Number"],axis = 1)

,CustomerID,First_Name,Last_Name,Paying Customer,Do_Not_Contact,street,Zip_Code,Street_Address
0,1001,Frodo,Baggins,Yes,No,Shire,123,Shire
1,1002,Abed,Nadir,No,Yes,None,93,West
3,1004,Dwight,Schrute,Yes,Y,"Pennsylvania, 18503",980,Paper
4,1005,Jon,Snow,Y,No,None,123,Dragons
5,1006,Ron,Swanson,Yes,Yes,None,768,City
6,1007,Jeff,Winger,No,No,None,1209,South
7,1008,Sherlock,Holmes,N,No,None,98,Clue
9,1010,Peter,Parker,Yes,No,New York,25,th
10,1011,Samwise,Gamgee,Yes,No,Shire,612,Shire
12,1013,Don,Draper,Yes,N,None,2039,Main
13,1014,Leslie,Knope,Yes,No,None,343,City
14,1015,Toby,Flenderson_,N,No,None,214,HR
15,1016,Ron,Weasley,No,N,None,2395,Hogwarts
16,1017,Michael,Scott,Yes,No,Pennsylvania,121,Paper
18,1019,Creed,Braton,N/a,Yes,None,NaN,N
19,1020,Anakin,Skywalker,Yes,N,Tatooine,910,Tatooine
20,1020,Anakin,Skywalker,Yes,N,Tatooine,910,Tatooine

In [ ]:
df = df.fillna("")

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,zip_code,street,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,123,Shire
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes,93 West Main Street,,93,West
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,"Pennsylvania, 18503",980,Paper
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No,123 Dragons Road,,123,Dragons
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes,768 City Parkway,,768,City
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,,1209,South
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,No,98 Clue Drive,,98,Clue
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No,25th Main Street,New York,25,th
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,612,Shire
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N,2039 Main Street,,2039,Main
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No,343 City Parkway,,343,City
14,1015,Toby,Flenderson_,304-762-246,214 HR Avenue,N,No,214 HR Avenue,,214,HR
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,,2395,Hogwarts
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,121,Paper
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,,,N
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,910,Tatooine
20,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,910,Tatooine

In [ ]:
df['Stree_Address'] = df['zip_code'].astype(str).str.extract(r'([A-Za-z ]+)', expand=False)

In [ ]:
df.drop(["street","Street_Address","zip_code","Phone_number","Address"],axis = 1)

KeyError: "['Phone_number'] not found in axis"

In [ ]:
df.isnull().sum()

In [ ]:
df